version: 0.2

phases:
  install:
    commands:
      - echo "Instalando Node.js y herramientas necesarias..."
      - nvm install 16 # Cambia a la versión de Node.js que usas en el proyecto
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo "Instalando dependencias del proyecto..."
      - npm install
  build:
    commands:
      - echo "Ejecutando pruebas..."
      - npm test # Ajusta este comando si no tienes pruebas configuradas o deseas omitirlas
  post_build:
    commands:
      - echo "Construcción completada."
artifacts:
  files:
    - "**/*" # Incluye todos los archivos del proyecto en los artefactos de compilación