version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # CAMBIA ESTO A LA VERSIÓN DE NODE QUE USES (ej: 18, 20)
    commands:
      - echo "Iniciando instalación de dependencias..."
      - npm ci # O npm install si no tienes package-lock.json
      - echo "Dependencias instaladas."

  pre_build:
    commands:
      - echo "Generando cliente de Prisma y aplicando migraciones..."
      - npx prisma generate
      - npx prisma migrate deploy # O npx prisma db push si usas SQLite
      - echo "Migraciones aplicadas."

  post_build:
    commands:
      - echo "Empaquetando artefactos para despliegue..."
      - mkdir build-output
      - cp -r node_modules build-output
      - cp -r prisma build-output
      - cp package.json build-output
      - cp package-lock.json build-output
      - cp -r src build-output # Copia tu código fuente
      - cp .env build-output # COPIA EL .ENV (debe estar en .gitignore)
      - zip -r application.zip build-output
      - echo "Artefactos empaquetados en application.zip"

artifacts:
  files:
    - application.zip
  discard-paths: yes