version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Cambia esta versión según tu proyecto
    commands:
      - echo "Instalando dependencias..."
      - npm install
  build:
    commands:
      - echo "Ejecutando pruebas y construyendo la aplicación..."
      - npm run build # Cambia este comando según tu necesidad o elimina si no tienes una fase de construcción
  post_build:
    commands:
      - echo "Listo para el despliegue"

artifacts:
  files:
    - "**/*"
  discard-paths: yes